import json
import os
import tempfile
from utils.logger import logger


class StateManager:
    """
    Manages the state of the pipeline, reading and writing to a JSON file.
    """
    def __init__(self, state_path: str):
        """
        Initializes the StateManager with the path to the state file.

        Args:
            state_path: The path to the JSON file where state is stored.
        """
        self.state_path = state_path
        # Ensure the directory for the state file exists.
        os.makedirs(os.path.dirname(self.state_path), exist_ok=True)

    def _write_atomic(self, data: dict):
        """
        Atomically writes data to the state file.

        This method first writes to a temporary file and then renames it to the
        final destination. This ensures that the state file is never left in a
        partially written or corrupted state.

        Args:
            data: The dictionary to write to the state file.
        """
        # Create a temporary file in the same directory.
        tmp_fd, tmp_path = tempfile.mkstemp(dir=os.path.dirname(self.state_path))
        with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
            # Write JSON data to the temporary file.
            json.dump(data, f, indent=2)
        # Atomically replace the old state file with the new one.
        os.replace(tmp_path, self.state_path)

    def read_state(self):
        """
        Reads the current state from the state file.

        Returns:
            A dictionary containing the current state, or an empty dictionary
            if the file does not exist or an error occurs.
        """
        try:
            with open(self.state_path, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data if isinstance(data, dict) else {}
        except Exception:
            # Return an empty dictionary if any exception occurs (e.g., file not found).
            return {}

    def reset_state(self):
        """
        Resets the state file to an empty dictionary.
        """
        logger.info("Resetting state.json")
        self._write_atomic({})

    def update_state(self, pipeline_id: str, current_stage: str, artifacts: dict):
        """
        Updates the state file with the current pipeline status.

        Args:
            pipeline_id: The unique ID of the current pipeline run.
            current_stage: The name of the current stage in the pipeline.
            artifacts: A dictionary of paths or data generated by the pipeline.
        """
        state = {
            "pipeline_id": pipeline_id,
            "current_stage": current_stage,
            "artifacts": artifacts
        }
        logger.info(f"Writing state: {state}")
        self._write_atomic(state)
